services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://localhost:27017/
    volumes:
      - .:/app
    command: ["python", "/app/app.py"]

volumes:
  mongo_data:


